# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da15e2760a2fa2eb0133d508be7286f1b6b6165dbb6999ef6a4019cfc68e2176ba677118c11aaf979d4816b236dd95a0fbd693dd831d09e1329bf36248a9086b

test:
  secret_key_base: 5c5d1f23940eeb3cfb473a84c4cff162182ef421be87e1571e7242cf58ff7c226f54628c263227c193cb6c6d12ade82d09f3c59acdd640b0ec2562284ba42536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
